import frappe

default_views = [
    {
        "columns": '[{"label":"ID","type":"Int","key":"name","width":"5rem"},{"label":"Subject","type":"Data","key":"subject","width":"25rem"},{"label":"Status","type":"Select","key":"status","width":"8rem"},{"label":"First response","type":"Datetime","key":"response_by","width":"8rem"},{"label":"Resolution","type":"Datetime","key":"resolution_by","width":"8rem"},{"label":"Assigned To","type":"MultipleAvatar","key":"_assign","width":"8rem"},{"label":"Customer","type":"Link","key":"customer","options":"HD Customer","width":"8rem"},{"label":"Priority","type":"Link","options":"HD Ticket Priority","key":"priority","width":"10rem"},{"label":"Type","type":"Link","options":"HD Ticket Type","key":"ticket_type","width":"11rem"},{"label":"Team","type":"Link","options":"HD Team","key":"agent_group","width":"10rem"},{"label":"Contact","type":"Link","key":"contact","options":"Contact","width":"8rem"},{"label":"Rating","type":"Rating","key":"feedback_rating","width":"10rem"},{"label":"Created","type":"Datetime","key":"creation","options":"Contact","width":"8rem"}]',
        "docstatus": 0,
        "doctype": "HD View",
        "dt": "HD Ticket",
        "filters": '{"sla":["is","set"],"agreement_status":["in","First Response Due, Resolution Due"],"status_category":["!=","Resolved"],"_assign":["LIKE","%@me%"]}',
        "group_by_field": None,
        "icon": "⏳",
        "is_customer_portal": 0,
        "is_default": 0,
        "is_standard": 1,
        "label": "SLA Due",
        "load_default_columns": 0,
        "modified": "2026-03-12 11:24:26.568571",
        "name": "STD-VIEW-SLA-DUE",
        "order_by": "response_by asc",
        "pinned": 0,
        "public": 1,
        "route_name": "TicketsAgent",
        "rows": '["name","subject","status","priority","ticket_type","agent_group","contact","agreement_status","response_by","resolution_by","customer","first_responded_on","modified","creation","_assign","resolution_date","feedback_rating","owner","modified_by"]',
        "type": "list",
        "user": "Administrator",
    },
    {
        "columns": '[{"label":"ID","type":"Int","key":"name","width":"5rem"},{"label":"Subject","type":"Data","key":"subject","width":"25rem"},{"label":"Status","type":"Select","key":"status","width":"8rem"},{"label":"First response","type":"Datetime","key":"response_by","width":"8rem"},{"label":"Resolution","type":"Datetime","key":"resolution_by","width":"8rem"},{"label":"Assigned To","type":"MultipleAvatar","key":"_assign","width":"8rem"},{"label":"Customer","type":"Link","key":"customer","options":"HD Customer","width":"8rem"},{"label":"Priority","type":"Link","options":"HD Ticket Priority","key":"priority","width":"10rem"},{"label":"Type","type":"Link","options":"HD Ticket Type","key":"ticket_type","width":"11rem"},{"label":"Team","type":"Link","options":"HD Team","key":"agent_group","width":"10rem"},{"label":"Contact","type":"Link","key":"contact","options":"Contact","width":"8rem"},{"label":"Rating","type":"Rating","key":"feedback_rating","width":"10rem"},{"label":"Created","type":"Datetime","key":"creation","options":"Contact","width":"8rem"}]',
        "docstatus": 0,
        "doctype": "HD View",
        "dt": "HD Ticket",
        "filters": '{"__assigned_on":["timespan","last week"],"status_category":"Open","_assign":["LIKE","%@me%"]}',
        "group_by_field": None,
        "icon": "🆕",
        "is_customer_portal": 0,
        "is_default": 0,
        "is_standard": 1,
        "label": "Recently Assigned Tickets",
        "load_default_columns": 0,
        "modified": "2026-03-13 13:10:59.427339",
        "name": "STD-VIEW-RECENTLY-ASSIGNED-TICKETS",
        "order_by": "creation desc",
        "pinned": 0,
        "public": 1,
        "route_name": "TicketsAgent",
        "rows": '["name","subject","status","priority","ticket_type","agent_group","contact","agreement_status","response_by","resolution_by","customer","first_responded_on","modified","creation","_assign","resolution_date","feedback_rating","owner","modified_by"]',
        "type": "list",
        "user": "Administrator",
    },
    {
        "columns": '[{"label":"ID","type":"Int","key":"name","width":"5rem"},{"label":"Subject","type":"Data","key":"subject","width":"25rem"},{"label":"Status","type":"Select","key":"status","width":"8rem"},{"label":"First response","type":"Datetime","key":"response_by","width":"8rem"},{"label":"Resolution","type":"Datetime","key":"resolution_by","width":"8rem"},{"label":"Assigned To","type":"MultipleAvatar","key":"_assign","width":"8rem"},{"label":"Customer","type":"Link","key":"customer","options":"HD Customer","width":"8rem"},{"label":"Priority","type":"Link","options":"HD Ticket Priority","key":"priority","width":"10rem"},{"label":"Type","type":"Link","options":"HD Ticket Type","key":"ticket_type","width":"11rem"},{"label":"Team","type":"Link","options":"HD Team","key":"agent_group","width":"10rem"},{"label":"Contact","type":"Link","key":"contact","options":"Contact","width":"8rem"},{"label":"Rating","type":"Rating","key":"feedback_rating","width":"10rem"},{"label":"Created","type":"Datetime","key":"creation","options":"Contact","width":"8rem"}]',
        "docstatus": 0,
        "doctype": "HD View",
        "dt": "HD Ticket",
        "filters": '{"_assign":["LIKE","%@me%"],"status_category":["!=","Resolved"],"last_customer_response":["is","set"],"last_agent_response":["is","not set"]}',
        "group_by_field": None,
        "icon": "📋",
        "is_customer_portal": 0,
        "is_default": 0,
        "is_standard": 1,
        "label": "Pending Tickets",
        "load_default_columns": 0,
        "modified": "2026-03-13 16:55:32.166889",
        "name": "STD-VIEW-PENDING-TICKETS",
        "order_by": "last_customer_response asc",
        "pinned": 0,
        "public": 1,
        "route_name": "TicketsAgent",
        "rows": '["name","subject","status","priority","ticket_type","agent_group","contact","agreement_status","response_by","resolution_by","customer","first_responded_on","modified","creation","_assign","resolution_date","feedback_rating","owner","modified_by"]',
        "type": "list",
        "user": "Administrator",
    },
    {
        "columns": '[{"label":"ID","type":"Data","key":"name","width":"5rem"},{"label":"Subject","type":"Data","key":"subject","width":"16rem","align":"left"},{"label":"Rating","type":"Rating","key":"feedback_rating","width":"8rem","align":"left"},{"label":"Contact","type":"Link","key":"contact","width":"10rem","align":"left"},{"label":"Feedback (Option)","type":"Link","key":"feedback","width":"10rem","align":"left"},{"label":"Feedback (Extra)","type":"Long Text","key":"feedback_extra","width":"10rem","align":"left"},{"label":"First response","type":"Datetime","key":"response_by","width":"7rem","align":"left"},{"label":"Resolution By","type":"Datetime","key":"resolution_by","width":"7rem","align":"left"}]',
        "docstatus": 0,
        "doctype": "HD View",
        "dt": "HD Ticket",
        "filters": '{"_assign":["LIKE","%@me%"],"feedback_rating":["is", "set"]}',
        "group_by_field": None,
        "icon": "⭐",
        "is_customer_portal": 0,
        "is_default": 0,
        "is_standard": 1,
        "label": "My Feedback",
        "load_default_columns": 0,
        "modified": "2026-03-17 12:42:22.891952",
        "name": "STD-VIEW-ALL-FEEDBACK",
        "order_by": "feedback_rating desc",
        "pinned": 0,
        "public": 1,
        "route_name": "TicketsAgent",
        "rows": '["name","owner","_seen","creation","modified_by","_assign","modified","subject","response_by","resolution_by","feedback_rating","feedback","feedback_extra","contact"]',
        "type": "list",
        "user": "Administrator",
    },
]


def add_default_views(for_existing_sites=False):

    for view in default_views:
        if not frappe.db.exists("HD View", view["name"]):
            doc = frappe.get_doc(view)
            doc.flags.name_set = True
            if for_existing_sites:
                doc.public = 0
            doc.insert(ignore_permissions=True)
