import unittest
from email import message_from_string

import frappe
from frappe.tests import IntegrationTestCase

from helpdesk.overrides.email_account import _failed_recipient, auto_generated_reason
from helpdesk.test_utils import make_ticket

# Real Gmail DSN headers -- the shape that caused the 95-mail loop on ticket 74703
GMAIL_BOUNCE = """\
Return-Path: <>
From: Mail Delivery Subsystem <mailer-daemon@googlemail.com>
To: support@frappe.io
Subject: Delivery Status Notification (Failure)
Auto-Submitted: auto-replied
Content-Type: multipart/report; report-type=delivery-status; boundary="b"

--b
Content-Type: text/plain

The email account that you tried to reach does not exist.
--b
Content-Type: message/delivery-status

Reporting-MTA: dns; googlemail.com

Final-Recipient: rfc822; dead@example.com
Action: failed
Status: 5.1.1
--b--
"""

OOO_REPLY = """\
Return-Path: <someone@example.com>
From: Someone <someone@example.com>
To: support@frappe.io
Subject: Out of office
Auto-Submitted: auto-replied

Back on Monday.
"""

# machine-originated mail that is not a reply to anything human
QUARANTINE_ALERT = """\
Return-Path: <postmaster@example.com>
From: Mail Gateway <postmaster@example.com>
To: support@frappe.io
Subject: Message held in quarantine
Auto-Submitted: auto-generated

A message addressed to you was held for review.
"""

# same DSN reaching us over POP3/Frappe Mail, where no MTA added a Return-Path
BARE_DSN = """\
From: Mail Delivery Subsystem <mailer-daemon@example.com>
To: support@frappe.io
Subject: Undelivered Mail Returned to Sender
Content-Type: multipart/report; report-type=delivery-status; boundary="b"

--b
Content-Type: text/plain

Recipient address rejected: User unknown.
--b--
"""

REAL_CUSTOMER_REPLY = """\
Return-Path: <omkar@batt.science>
From: Omkar <omkar@batt.science>
To: support@frappe.io
Subject: Re: URGENT : Tickets raised outside working hours

Any update on this?
"""


class TestAutoGeneratedReason(unittest.TestCase):
    def test_gmail_bounce_is_dropped(self):
        # the DSN marker must win over Auto-Submitted, the comment wording keys off it
        self.assertEqual(
            auto_generated_reason(message_from_string(GMAIL_BOUNCE)),
            "delivery status notification",
        )

    def test_failed_recipient_read_from_delivery_status(self):
        self.assertEqual(
            _failed_recipient(message_from_string(GMAIL_BOUNCE)), "dead@example.com"
        )

    def test_failed_recipient_absent_when_dsn_names_none(self):
        self.assertIsNone(_failed_recipient(message_from_string(BARE_DSN)))

    def test_out_of_office_is_kept(self):
        # auto-replied threads onto its ticket so agents see it
        self.assertIsNone(auto_generated_reason(message_from_string(OOO_REPLY)))

    def test_auto_generated_alert_is_dropped(self):
        self.assertEqual(
            auto_generated_reason(message_from_string(QUARANTINE_ALERT)),
            "Auto-Submitted: auto-generated",
        )

    def test_dsn_without_return_path_is_dropped(self):
        # only the RFC 3464 report type is left to go on
        self.assertEqual(
            auto_generated_reason(message_from_string(BARE_DSN)),
            "delivery status notification",
        )

    def test_legacy_x_auto_generated_still_dropped(self):
        msg = message_from_string(REAL_CUSTOMER_REPLY)
        msg["X-Auto-Generated"] = "auto-replied"
        self.assertTrue(auto_generated_reason(msg))

    def test_real_reply_is_kept(self):
        self.assertIsNone(
            auto_generated_reason(message_from_string(REAL_CUSTOMER_REPLY))
        )

    def test_missing_headers_do_not_look_like_a_bounce(self):
        # no Return-Path / Auto-Submitted at all -- must not be mistaken for a DSN
        msg = message_from_string("From: a@b.com\nTo: support@frappe.io\n\nhi")
        self.assertIsNone(auto_generated_reason(msg))

    def test_auto_submitted_no_is_kept(self):
        msg = message_from_string(REAL_CUSTOMER_REPLY)
        msg["Auto-Submitted"] = "no"
        self.assertIsNone(auto_generated_reason(msg))

    def test_auto_submitted_no_with_parameters_is_kept(self):
        # RFC 3834 allows parameters after the value -- still human-sent
        msg = message_from_string(REAL_CUSTOMER_REPLY)
        msg["Auto-Submitted"] = "no; owner=someone@example.com"
        self.assertIsNone(auto_generated_reason(msg))


@unittest.skipUnless(
    getattr(frappe.local, "site", None), "needs a site (run via bench run-tests)"
)
class TestParkedMailTicketComment(IntegrationTestCase):
    """A parked bounce or auto-reply that belongs to a ticket must leave an
    internal comment there, so agents still see what happened."""

    def setUp(self):
        super().setUp()
        self.ticket = make_ticket(
            subject="Parked mail comment test",
            raised_by="parked-mail-customer@example.com",
        )
        self.message_id = f"reply-{self.ticket.name}@test.local"
        frappe.get_doc(
            {
                "doctype": "Communication",
                "communication_type": "Communication",
                "communication_medium": "Email",
                "sent_or_received": "Sent",
                "subject": "Re: Parked mail comment test",
                "sender": "support@example.com",
                "recipients": self.ticket.raised_by,
                "reference_doctype": "HD Ticket",
                "reference_name": self.ticket.name,
                "message_id": self.message_id,
            }
        ).insert(ignore_permissions=True)
        self.account = frappe.get_last_doc("Email Account")

    def ticket_comments(self):
        return frappe.get_all(
            "HD Ticket Comment",
            filters={"reference_ticket": self.ticket.name},
            pluck="content",
        )

    def notify(self, raw):
        msg = message_from_string(raw)
        reason = auto_generated_reason(msg)
        self.assertIsNotNone(reason)
        self.account.notify_ticket_of_parked_mail(raw, msg, reason)

    def test_bounce_leaves_delivery_failed_comment(self):
        self.notify(f"In-Reply-To: <{self.message_id}>\n" + GMAIL_BOUNCE)

        comments = self.ticket_comments()
        self.assertEqual(len(comments), 1)
        self.assertIn("Delivery failed", comments[0])
        self.assertIn("dead@example.com", comments[0])

    def test_auto_generated_reply_leaves_comment(self):
        self.notify(f"In-Reply-To: <{self.message_id}>\n" + QUARANTINE_ALERT)

        comments = self.ticket_comments()
        self.assertEqual(len(comments), 1)
        self.assertIn("Auto-reply received from postmaster@example.com", comments[0])

    def test_unmatched_bounce_leaves_no_comment(self):
        self.notify(GMAIL_BOUNCE)

        self.assertEqual(self.ticket_comments(), [])


@unittest.skipUnless(
    getattr(frappe.local, "site", None), "needs a site (run via bench run-tests)"
)
class TestHandleBadEmailsRecordsAllTransports(IntegrationTestCase):
    """The framework skips the Unhandled Email record for non-IMAP accounts;
    the override must leave a trace for POP3/Frappe Mail drops too."""

    REASON = "test: bounce trace"

    def tearDown(self):
        frappe.db.delete("Unhandled Email", {"reason": self.REASON})
        # handle_bad_emails commits, so the cleanup must commit too or the
        # class-level rollback would resurrect the row
        frappe.db.commit()  # nosemgrep
        super().tearDown()

    def test_non_imap_drop_lands_in_unhandled_email(self):
        account = frappe.get_last_doc("Email Account")
        account.use_imap = 0

        account.handle_bad_emails(None, GMAIL_BOUNCE, self.REASON)

        row = frappe.db.get_value(
            "Unhandled Email",
            {"reason": self.REASON},
            ["email_account", "message_id"],
            as_dict=True,
        )
        self.assertIsNotNone(row)
        self.assertEqual(row.email_account, account.name)


if __name__ == "__main__":
    unittest.main()
