import unittest
from email import message_from_string

from helpdesk.overrides.email_account import auto_generated_reason

# Real Gmail DSN headers -- the shape that caused the 95-mail loop on ticket 74703
GMAIL_BOUNCE = """\
Return-Path: <>
From: Mail Delivery Subsystem <mailer-daemon@googlemail.com>
To: support@frappe.io
Subject: Delivery Status Notification (Failure)
Auto-Submitted: auto-replied
Content-Type: multipart/report; report-type=delivery-status; boundary="b"

--b
Content-Type: text/plain

The email account that you tried to reach does not exist.
--b--
"""

OOO_REPLY = """\
Return-Path: <someone@example.com>
From: Someone <someone@example.com>
To: support@frappe.io
Subject: Out of office
Auto-Submitted: auto-replied

Back on Monday.
"""

# same DSN reaching us over POP3/Frappe Mail, where no MTA added a Return-Path
BARE_DSN = """\
From: Mail Delivery Subsystem <mailer-daemon@example.com>
To: support@frappe.io
Subject: Undelivered Mail Returned to Sender
Content-Type: multipart/report; report-type=delivery-status; boundary="b"

--b
Content-Type: text/plain

Recipient address rejected: User unknown.
--b--
"""

REAL_CUSTOMER_REPLY = """\
Return-Path: <omkar@batt.science>
From: Omkar <omkar@batt.science>
To: support@frappe.io
Subject: Re: URGENT : Tickets raised outside working hours

Any update on this?
"""


class TestAutoGeneratedReason(unittest.TestCase):
    def test_gmail_bounce_is_dropped(self):
        self.assertTrue(auto_generated_reason(message_from_string(GMAIL_BOUNCE)))

    def test_out_of_office_is_dropped(self):
        self.assertTrue(auto_generated_reason(message_from_string(OOO_REPLY)))

    def test_dsn_without_return_path_is_dropped(self):
        # only the RFC 3464 report type is left to go on
        self.assertEqual(
            auto_generated_reason(message_from_string(BARE_DSN)),
            "delivery status notification",
        )

    def test_legacy_x_auto_generated_still_dropped(self):
        msg = message_from_string(REAL_CUSTOMER_REPLY)
        msg["X-Auto-Generated"] = "auto-replied"
        self.assertTrue(auto_generated_reason(msg))

    def test_real_reply_is_kept(self):
        self.assertIsNone(
            auto_generated_reason(message_from_string(REAL_CUSTOMER_REPLY))
        )

    def test_missing_headers_do_not_look_like_a_bounce(self):
        # no Return-Path / Auto-Submitted at all -- must not be mistaken for a DSN
        msg = message_from_string("From: a@b.com\nTo: support@frappe.io\n\nhi")
        self.assertIsNone(auto_generated_reason(msg))

    def test_auto_submitted_no_is_kept(self):
        msg = message_from_string(REAL_CUSTOMER_REPLY)
        msg["Auto-Submitted"] = "no"
        self.assertIsNone(auto_generated_reason(msg))

    def test_auto_submitted_no_with_parameters_is_kept(self):
        # RFC 3834 allows parameters after the value -- still human-sent
        msg = message_from_string(REAL_CUSTOMER_REPLY)
        msg["Auto-Submitted"] = "no; owner=someone@example.com"
        self.assertIsNone(auto_generated_reason(msg))


if __name__ == "__main__":
    unittest.main()
