/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const LucideAlignJustify: typeof import("~icons/lucide/align-justify")["default"];
  const LucideFileSearch: typeof import("~icons/lucide/file-search")["default"];
  const LucideKeyboard: typeof import("~icons/lucide/keyboard")["default"];
  const LucideSearch: typeof import("~icons/lucide/search")["default"];
}
