/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const LucideAlignJustify: typeof import('~icons/lucide/align-justify')['default']
  const LucideCornerUpLeft: typeof import('~icons/lucide/corner-up-left')['default']
  const LucideFileSearch: typeof import('~icons/lucide/file-search')['default']
  const LucideMessageCircle: typeof import('~icons/lucide/message-circle')['default']
  const LucideTag: typeof import('~icons/lucide/tag')['default']
}
