/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const LucideFileSearch: typeof import('~icons/lucide/file-search')['default']
  const LucideSearch: typeof import('~icons/lucide/search')['default']
}
